// <auto-generated />
using System;
using Food_Application.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Food_Application.Migrations
{
    [DbContext(typeof(ApplicatioDbContext))]
    [Migration("20220803071011_update")]
    partial class update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("Food_Application.Entity.Dish", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("portions")
                        .HasColumnType("REAL");

                    b.Property<double?>("price")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.ToTable("Dishs");
                });

            modelBuilder.Entity("Food_Application.Entity.Ingridien", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Dishid")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("mas")
                        .HasColumnType("REAL");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("price")
                        .HasColumnType("REAL");

                    b.Property<double?>("quantity")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.HasIndex("Dishid");

                    b.ToTable("ingridiens");
                });

            modelBuilder.Entity("Food_Application.Entity.Ingridien", b =>
                {
                    b.HasOne("Food_Application.Entity.Dish", null)
                        .WithMany("ingridiens")
                        .HasForeignKey("Dishid");
                });

            modelBuilder.Entity("Food_Application.Entity.Dish", b =>
                {
                    b.Navigation("ingridiens");
                });
#pragma warning restore 612, 618
        }
    }
}
